# gitlab scanning

stages:
  - test

test:
    script:
        - apt-get update -qy
        - apt-get install -y python3-pip
        - pip install -r requirements.txt
        - python3 -m unittest test_faucet_v1.py
